import { UserRole } from 'src/modules/users/entities/user.entity';
import { TenderStatus } from '../entities/tender.entity';

export const GetAllTendersPolicy = {
  allowedFields: {
    [UserRole.SUPER_ADMIN]: [
      'tender_status',
      'created_by_id',
      'industry_id',
      'size_id',
      'company_type_id',
      'location',
      'price_min',
      'price_max',
      'page',
      'per_page',
      'search',
      'exclude_archived',
      'organization_bidder_id',
      'exclude_expired',
      'start_date',
      'end_date'
    ],
    [UserRole.ADMIN]: [
      'tender_status',
      'created_by_id',
      'industry_id',
      'size_id',
      'company_type_id',
      'location',
      'price_min',
      'price_max',
      'page',
      'per_page',
      'search',
      'exclude_archived',
      'organization_bidder_id',
      'exclude_expired',
      'start_date',
      'end_date'
    ],
    [UserRole.ORGANIZATION]: [
      'tender_status',
      'created_by_id',
      'industry_id',
      'size_id',
      'company_type_id',
      'location',
      'price_min',
      'price_max',
      'page',
      'per_page',
      'search',
      'exclude_mine',
      'exclude_archived',
      'exclude_already_bidded',
      'organization_bidder_id',
      'exclude_expired',
      'start_date',
      'end_date'
    ],
    [UserRole.TRANSPORTER]: [
      'tender_status',
      'created_by_id',
      'industry_id',
      'size_id',
      'company_type_id',
      'location',
      'price_min',
      'price_max',
      'page',
      'per_page',
      'search',
      'exclude_archived',
      'exclude_expired',
      'start_date',
      'end_date'
    ],
  },
  allowedValues: {
    tender_status: {
      [UserRole.SUPER_ADMIN]: Object.values(TenderStatus),
      [UserRole.ADMIN]: Object.values(TenderStatus),
      [UserRole.ORGANIZATION]: [TenderStatus.APPROVED],
      [UserRole.TRANSPORTER]: [TenderStatus.APPROVED],
    },
  },
};
